pluginManagement {
    repositories {
        //镜像仓库,无法连接源仓库自行启用镜像仓库,不要提交修改
        maven { url "https://maven-central-asia.storage-download.googleapis.com/maven2/" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        gradlePluginPortal()
        mavenCentral()
        jcenter()
        google()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        //镜像仓库,无法连接源仓库自行启用镜像仓库,不要提交修改
        maven { url "https://maven-central-asia.storage-download.googleapis.com/maven2/" }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2' }
        mavenCentral()
        jcenter()
        google()
        flatDir {
            dirs "$rootDir/app/libs"
        }
        maven {
            url "https://jitpack.io"
        }
        maven {
            url "http://4thline.org/m2"
            allowInsecureProtocol = true
        }
    }
}
include ':app'
include ':hook'
include ':tvbus'
include ':catvod'
include ':pyramid'
include ':quickjs'
include ':thunder'
include ':jianpian'
include ':forcetech'
include ':ijkplayer'
rootProject.name = "TV"
