name: Build Mobile APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build Mobile APK (Arm64)
        run: ./gradlew :app:assembleMobileJavaArm64_v8aRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mobile-arm64-release-apk
          path: app/build/outputs/apk/**/*.apk