name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4  # Use the latest version of setup-node
        with:
          node-version: 16  # Explicitly set Node.js version to 16

      - uses: actions/checkout@v4 

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Release Apk Sign
        run: |
          cp -f ${{ github.workspace }}/.github/workflows/xxtv.jks app/xxtv.jks
          sed -i '$a\RELEASE_STORE_FILE=./xxtv.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=key0'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=123456'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=123456'         ./gradle.properties

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleRelease --parallel --daemon --warning-mode all --stacktrace

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.fongmi.android.tv
          path: ${{ github.workspace }}/apk/*
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ok-tv_4.x
          tag_name: 4.x          
          body_path: ${{ github.workspace }}/README.md
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/apk/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
